import type { Metadata } from "next";

import "./globals.css";
import Providers from "./components/Providers";
import Navbar from "./components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-screen flex flex-col bg-[linear-gradient(220deg,#374151,#000,#4c1d95)] text-white">        <Providers>
        <Navbar />
        {children}
      </Providers>
      </body>
    </html>
  );
}
